# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none

pool:
  vmImage: 'macOS-latest'

steps:
- checkout: self
  persistCredentials: true

- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
    script: |
     Set-DisplayResolution -Width 420 -Height 1368 -Force
  displayName: 'Install Node.js'

- script: |
    npm install sfdx-cli --global 
    npm install
    ./runMain.sh
    
  displayName: 'npm install and test run.'
