# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: SeleniumTest

on:
  workflow_dispatch:
     inputs:
      debug:
        description: 'print debug log'
        required: false
        default: 'true'
      slack_post_image:
        description: ' post file to slack'
        required: false
        default: 'true'
      slack_post_text:
        description: 'post text to slack'
        required: false
        default: 'true'
jobs:
  build:

    runs-on: macOS-latest

    strategy:
      matrix:
        node-version: [ 12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: echo "SLACK_TOKEN=${{ secrets.SLACK_BOT_TOKEN }}" >> $GITHUB_ENV
    - run: echo "SLACK_SECRET_KEY=${{ secrets.SLACK_SIGNING_SECRET }}" >> $GITHUB_ENV
    - run: echo "SLACK_CHANNEL=${{ secrets.SLACK_CHANNEL }}" >> $GITHUB_ENV
    - run: echo "SLACK_POST_IMAGE=${{ github.event.inputs.slack_post_image }}" >> $GITHUB_ENV
    - run: echo "SLACK_POST_TEXT=${{ github.event.inputs.slack_post_text }}" >> $GITHUB_ENV
    - run: echo "DEBUG=${{ github.event.inputs.debug }}" >> $GITHUB_ENV
    - run: echo "SFDX_AUTH_URL=${{ secrets.SFDX_AUTH_URL }}" >> $GITHUB_ENV
    - run: npm install sfdx-cli --global 
    - run: npm install
    

    - run: ./runMain.sh
