# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: SeleniumTest

on:
  workflow_dispatch:
     inputs:
      debug:
        description: 'print debug log'
        required: false
        default: 'true'
      slack_post_image:
        description: ' post file to slack'
        required: false
        default: 'true'
      slack_post_text:
        description: 'post text to slack'
        required: false
        default: 'true'
      # slack_secret_key:
      #   description: 'Slack Signing Secret'
      #   required: false
      #   default: ''
      # slack_token:
      #   description: 'Slack BOT Oauth Token'
      #   required: false
      #   default: ''
      # slack_channel:
      #   description: 'Slack Channel'
      #   required: false
      #   default: ''
      git_email:
        description: 'git email'
        required: false
        default: ''
      git_username:
        description: 'git username'
        required: false
        default: ''
      # sfdx_auth_url_key:
      #   description: 'Sfdx Auth URL(force://PlatformCLI::<here>@domain.com)'
      #   required: false
      #   default: ''
      # sfdx_auth_url_domain:
      #   description: 'Sfdx Auth URL(force://PlatformCLI::*****@<here>)'
      #   required: false
      #   default: ''
jobs:
  build:

    runs-on: macOS-latest

    strategy:
      matrix:
        node-version: [ 12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
      echo "SLACK_SECRET_KEY=${{ secrets.SSKEY }}" >> $GITHUB_ENV
      echo "SLACK_TOKEN=${{ secrets.SLACK_BOT_TOKEN }}" >> $GITHUB_ENV
      echo "SLACK_CHANNEL=${{ secret.SLACK_CHANNEL }}" >> $GITHUB_ENV
      echo "SLACK_POST_IMAGE=${{ github.event.inputs.slack_post_image }}" >> $GITHUB_ENV
      echo "SLACK_POST_TEXT=${{ github.event.inputs.slack_post_text }}" >> $GITHUB_ENV
      echo "DEBUG=${{ github.event.inputs.debug }}" >> $GITHUB_ENV
      echo "GIT_EMAIL=${{ github.event.inputs.git_email }}" >> $GITHUB_ENV
      echo "GIT_USERNAME=${{ github.event.inputs.git_username }}" >> $GITHUB_ENV
      echo "SFDX_AUTH_URL=${{ secrets.SFDX_AUTH_URL }}" >> $GITHUB_ENV
      npm install sfdx-cli --global 
      npm install
    
    - run: ./runMain.sh
