# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

#export SLACK_TOKEN='<Slack BOT Oauth Token>'
# export SLACK_CHANNEL='<Slack Channel ID>'
# export SLACK_SECRET_KEY='<Signing Secret>'
# export SLACK_POST_IMAGE='false'
# export SLACK_POST_TEXT='false'
# export DEBUG='true'
# git email
# git uname
on:
  workflow_dispatch:
     inputs:
      debug:
        description: 'print debug log'
        required: false
        default: 'true'
      slack_post_image:
        description: ' post file to slack'
        required: false
        default: 'true'
      slack_post_text:
        description: 'post text to slack'
        required: false
        default: 'true'
      slack_secret_key:
        description: 'Slack Signing Secret'
        required: false
        default: ''
      slack_token:
        description: 'Slack BOT Oauth Token'
        required: false
        default: ''
      slack_channel:
        description: 'Slack Channel'
        required: false
        default: ''
      git_email:
        description: 'git email'
        required: false
        default: ''
      git_username:
        description: 'git username'
        required: false
        default: ''
      sfdx_auth_url:
        description: 'Sfdx Auth URL'
        required: false
        default: ''
jobs:
  build:

    runs-on: macOS-latest

    strategy:
      matrix:
        node-version: [ 12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      env: 
        SLACK_TOKEN: ${{ github.event.inputs.slack_token }}
        SLACK_CHANNEL: ${{ github.event.inputs.slack_channel }}
        SLACK_SECRET_KEY: ${{ github.event.inputs.slack_secret_key }}
        SLACK_POST_IMAGE: ${{ github.event.inputs.slack_post_image }}
        SLACK_POST_TEXT: ${{ github.event.inputs.slack_post_text }}
        DEBUG: ${{ github.event.inputs.debug }}
        GIT_EMAIL: ${{ github.event.inputs.git_email }}
        GIT_USERNAME: ${{ github.event.inputs.git_username }}
        SFDX_AUTH_URL: ${{ github.event.inputs.sfdx_auth_url }}

    # - run: npm install sfdx-cli --global 
    # - run: npm install
    
    - run: ./runMain.sh
